"""init

Revision ID: 7c7d50333c3f
Revises:
Create Date: 2025-09-20 19:15:47.708324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c7d50333c3f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diseases",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("specialty", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "examinations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "modality",
            sa.Enum("lab", "instrumental", "other", name="exam_modality_enum"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("recorded_age", sa.Integer(), nullable=True),
        sa.Column(
            "sex", sa.Enum("male", "female", "other", name="sex_enum"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visits",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("patient_id", sa.BigInteger(), nullable=False),
        sa.Column("doctor_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_visits_patient_id"), "visits", ["patient_id"], unique=False
    )
    op.create_table(
        "anamneses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("visit_id", sa.BigInteger(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["visit_id"], ["visits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("visit_id"),
    )
    op.create_table(
        "diagnoses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("visit_id", sa.BigInteger(), nullable=False),
        sa.Column("disease_id", sa.BigInteger(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["disease_id"], ["diseases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["visit_id"], ["visits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnoses_disease_id"), "diagnoses", ["disease_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnoses_visit_id"), "diagnoses", ["visit_id"], unique=False
    )
    op.create_table(
        "diagnosis_suggestions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("visit_id", sa.BigInteger(), nullable=False),
        sa.Column("disease_id", sa.BigInteger(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["disease_id"], ["diseases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["visit_id"], ["visits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "visit_id", "disease_id", name="uq_suggestion_visit_disease"
        ),
    )
    op.create_index(
        op.f("ix_diagnosis_suggestions_disease_id"),
        "diagnosis_suggestions",
        ["disease_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnosis_suggestions_visit_id"),
        "diagnosis_suggestions",
        ["visit_id"],
        unique=False,
    )
    op.create_index(
        "ix_suggestion_prob_desc",
        "diagnosis_suggestions",
        ["probability"],
        unique=False,
    )
    op.create_table(
        "referral_suggestions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("visit_id", sa.BigInteger(), nullable=False),
        sa.Column("specialty", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["visit_id"], ["visits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_suggestions_visit_id"),
        "referral_suggestions",
        ["visit_id"],
        unique=False,
    )
    op.create_table(
        "visit_examinations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("visit_id", sa.BigInteger(), nullable=False),
        sa.Column("examination_name", sa.String(length=128), nullable=False),
        sa.Column("result_text", sa.Text(), nullable=True),
        sa.Column(
            "result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("s3_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["visit_id"], ["visits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_visit_examinations_visit_id"),
        "visit_examinations",
        ["visit_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_visit_examinations_visit_id"), table_name="visit_examinations"
    )
    op.drop_table("visit_examinations")
    op.drop_index(
        op.f("ix_referral_suggestions_visit_id"), table_name="referral_suggestions"
    )
    op.drop_table("referral_suggestions")
    op.drop_index("ix_suggestion_prob_desc", table_name="diagnosis_suggestions")
    op.drop_index(
        op.f("ix_diagnosis_suggestions_visit_id"), table_name="diagnosis_suggestions"
    )
    op.drop_index(
        op.f("ix_diagnosis_suggestions_disease_id"), table_name="diagnosis_suggestions"
    )
    op.drop_table("diagnosis_suggestions")
    op.drop_index(op.f("ix_diagnoses_visit_id"), table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_disease_id"), table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_table("anamneses")
    op.drop_index(op.f("ix_visits_patient_id"), table_name="visits")
    op.drop_table("visits")
    op.drop_table("patients")
    op.drop_table("examinations")
    op.drop_table("diseases")
    # ### end Alembic commands ###
